# Generated by Django 4.2.20 on 2025-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название фильма')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Фантази', 'Фантази'), (' Ужасы', 'Ужасы'), ('Триллер', 'Триллер')], default='Ужасы', max_length=100, verbose_name='Укажите жанр')),
                ('author', models.CharField(default='Иванов Иван', max_length=100)),
                ('description', models.TextField(verbose_name='Укажите описание фильма')),
                ('trailer_film', models.URLField(verbose_name='Встаьте ссылку трейлера фильма')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
